apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapprs
  labels:
    app: appmyapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      name: myapp
      labels:
        app: myapp
    spec:
      containers:
        - name: nginx
          image: nginx